### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by daxtens** [andreiw/ppc64le_hello#5]
Would you mind adding a license file please? I'm not picky about which one.

**Comment by andreiw** [comment]
Ok, will be more explicit about it and add a LICENSE file. It's GPL given
it's inheritance.

A

On Wed, Jun 3, 2015 at 12:54 AM, Daniel Axtens notifications@github.com
wrote:

> Would you mind adding a license file please? I'm not picky about which one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andreiw/ppc64le_hello/issues/5.

## 

A
